title: 'DEFNE '
description: AKSDHFHFVVJNVVNR
template:
  repo: defne-template
  name: defne
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
